### PR TITLE
docs: updates tool for ADR management to trestle

### LINKED ISSUE #314: Update ADR to use trestle for markdown validation
**Is your feature request related to a problem? Please describe.**

`trestle` is able to assist with authoring and validation of markdown that can support `ADRs`. The current ADR template is hindering process on #305.

**Describe the solution you'd like**
- Recreate the template using `trestle` for authoring and validation

**Describe alternatives you've considered**
- Use a custom template with `adr-tools`. `trestle` is preferable because it is being actively maintained and is already a project dependency.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jpower432**
## Description

Keeps the original intent of ADR management and updates solution to use `trestle` to manage the custom ADR template.

Fixes #314 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

- [X] Validated locally

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gvauter — APPROVED** [review]
LGTM, one thought on the status field.

**Comment by jpower432** [comment]
> LGTM, one thought on the status field.

@gvauter Not seeing a comment pertaining to the status field.

**Comment by gvauter** [comment]
> > LGTM, one thought on the status field.
> 
> @gvauter Not seeing a comment pertaining to the status field.

@jpower432 Apologies - my comment was around the potential desire for a "proposed" status, similar to what is mentioned [here](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions).  I believe all the current status values apply after a decision has been made, but do we want a status to represent ADRs that are under review/discussion?

**Comment by jpower432** [comment]
> @jpower432 Apologies - my comment was around the potential desire for a "proposed" status, similar to what is mentioned [here](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions). I believe all the current status values apply after a decision has been made, but do we want a status to represent ADRs that are under review/discussion?

Good catch. I think an ADR that has been submitted via the PR process could have a proposed status.

**Review by gvauter — APPROVED** [review]
LGTM

**Pull request merged**
